name: Compile

on:
  push:
    branches:
      - 'master'
      - '*.*.*'
    tags:
      - '*.*.*'

  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Compile sourcepawn
      uses: rumblefrog/setup-sp@v1.0.1
    
    - run: |
        mkdir -p addons/sourcemod/plugins

        wget "https://forums.alliedmods.net/attachment.php?attachmentid=188744&d=1618607414" -O system2.zip
        unzip -o system2.zip -d addons/sourcemod/
        
        wget "https://github.com/KyleSanderson/SteamWorks/releases/download/1.2.3c/package-lin.tgz" -O steamworks.tgz
        tar -xf steamworks.tgz --strip-components=1

        spcomp \
          scripting/connector.sp \
          -o scripting/connector.smx
